### ISSUE TITLE
Cannot read property key of undefined

### ISSUE THREAD

**Issue by arlemi** [orbit-love/community-js-stackoverflow-orbit#13]
Hey there! 

When trying to set up the StackOverflow integration through GitHub Actions I'm seeing the following error: 
![unknown](https://user-images.githubusercontent.com/5029719/143570567-95bb0a70-51af-4f88-a537-0d1cc881ab84.png)

- The Orbit Credentials are correct as they are also being used in the YouTube integration which pushes the content correctly
- It seems to be pulling the data from StackOverflow correctly

I'm wondering if this could be related to #4 as it also seemed to be something to do with the way errors are handled. Any idea @phazonoverload ?

**Comment by phazonoverload** [comment]
Hey @arlemi hope you’re well! I no longer work at Orbit but I’m sure one of the remaining Orbit folks will be able to help. Can I recommend taking this to the community Discord to ensure someone sees it?

**Comment by arlemi** [comment]
@phazonoverload Doing well, hope you are too! the Discord is where my journey started, I was hoping to get more eyes here but I also just realised we're right in the middle of Thanksgiving so I'll give it some time. 🙂

**Comment by phacks** [comment]
Hey @arlemi! I looked into this and I believe the error comes from the `ORBIT_WORKSPACE_ID` secret that might point to a non-existent workspace. It is possible to change a workspace slug within Orbit (and we don’t yet do smart redirections in that case à la GitHub), which is what might have happened in your case.

I will be looking into displaying a better error message in this case—in the meantime, let me know if updating the `ORBIT_WORKSPACE_ID` worked!

**Comment by phacks** [comment]
Found a way to reproduce the issue:

- Set up the StackOverflow GitHub action (others might also be affected), with a correct Orbit API key but a nonexistent Orbit Workspace ID (`thisworkspacedoesnotexist1234`)
- Run the action for a popular SO tag, like `react` (so that we’ll have recent questions to create activities for)
- The error `Cannot read property key of undefined` is thrown

**Comment by arlemi** [comment]
@phacks Not sure what I had in there before but updating it worked! I wish Github Actions would actually raise an error in this case because this made me realise that the YT integration had been broken for a week without me noticing it.

**Comment by colinloretz** [comment]
@arlemi agreed on raising errors from Github Actions! We're looking at some options on that front until we can get these integrations built into Orbit.

Nice work @phacks! I'll give that a review.
