### ISSUE TITLE
Unregistered StackOverflow user causes the script to split on undefined value 

### ISSUE THREAD

**Issue by sindbach** [orbit-love/community-js-stackoverflow-orbit#16]
While trying to ingest questions from StackOverflow using v0.3.7, encountering an error: 

```sh
➜ npx @orbit-love/stackoverflow --questions --tag=mongodb--hours=100
Got the last 100 hours worth of questions for a total of 223 items
TypeError: Cannot read properties of undefined (reading 'split')
    at /Users/anonymous/.npm/_npx/fb52ec0068aafe47/node_modules/@orbit-love/stackoverflow/src/questions.js:84:59
    at Array.map (<anonymous>)
    at /Users/anonymous/.npm/_npx/fb52ec0068aafe47/node_modules/@orbit-love/stackoverflow/src/questions.js:69:38
    at new Promise (<anonymous>)
    at Object.prepare (/Users/anonymous/.npm/_npx/fb52ec0068aafe47/node_modules/@orbit-love/stackoverflow/src/questions.js:64:12)
    at OrbitStackOverflow.prepareQuestions (/Users/anonymous/.npm/_npx/fb52ec0068aafe47/node_modules/@orbit-love/stackoverflow/src/index.js:31:26)
    at main (/Users/anonymous/.npm/_npx/fb52ec0068aafe47/node_modules/@orbit-love/stackoverflow/src/bin.js:42:64)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

This is because on https://github.com/orbit-love/community-js-stackoverflow-orbit/blob/0.3.7/src/questions.js#L84 the code is trying to `split` on an undefined owner value. 

In this particular case, it was caused by a StackOverflow entry https://stackoverflow.com/questions/71464785/error-serializing-meetups0-title-returned-from-getstaticprops-in 
Where the user is unregistered.

**Comment by sindbach** [comment]
PR: https://github.com/orbit-love/community-js-stackoverflow-orbit/pull/17

**Comment by sindbach** [comment]
While waiting for the PR for this issue to be merged and published, you can use `@sindbach/orbit-love.stackoverflow` in the meantime. 

https://www.npmjs.com/package/@sindbach/orbit-love.stackoverflow

**Comment by colinloretz** [comment]
@sindbach Thanks for the PR! Sorry for the delay, I'll take a peek at this tomorrow and get it merged/published!

**Comment by mxdavis** [comment]
Thanks @sindbach! Publish 0.3.8.
