### ISSUE TITLE
Add error handling for bad query -> results.items is undefined.

### ISSUE THREAD

**Issue by jpoehnelt** [orbit-love/community-js-stackoverflow-orbit#2]
This might be caused by a bad configuration and an error response where `results.items` is undefined? 

https://github.com/googlemaps/.github/pull/40/checks?check_run_id=2633217792

**Comment by phazonoverload** [comment]
Let me look into this now

**Comment by jpoehnelt** [comment]
Was a bad key copy paste. Probably can decrease priority of this.

**Comment by phazonoverload** [comment]
Good to know! As it happens I just released orbit-love/activities today which has better error handling. It'll be made better again next week and then I'll update existing npm packages with it. Thanks for the update!

**Comment by phazonoverload** [comment]
This has just been fixed as part of 0.3.0.
