### ISSUE TITLE
Add support for answers.

### ISSUE THREAD

**Issue by jpoehnelt** [orbit-love/community-js-stackoverflow-orbit#3]
The community of users providing answers can be as important to track as those asking questions. :)

**Comment by phazonoverload** [comment]
In the backlog! I'll let you know when this is available 😄

**Comment by phazonoverload** [comment]
Coming this week hopefully 😄

**Comment by phazonoverload** [comment]
Hey! Just an update that this will take quite a bit longer than expected. To build this in a way which allows for robust usage without hitting rate limits is a challenge. And it's a challenge we'll overcome but it may take a little while. I'll leave this issue open in the meantime.

**Comment by phazonoverload** [comment]
Done! If you add `--answers` to your CLI command and you should now pull those in as well for any questions posted in the last 28 days 😄
