### ISSUE TITLE
Error is undefined

### ISSUE THREAD

**Issue by jpoehnelt** [orbit-love/community-js-stackoverflow-orbit#4]
Some runs fail with error undefined in the throw call.

https://github.com/googlemaps/.github/runs/2718886570?check_suite_focus=true

```
npx: installed 71 in 3.873s
/home/runner/.npm/_npx/1694/lib/node_modules/@orbit-love/stackoverflow/src/orbit.js:27
                            throw new Error(error)
                                            ^

ReferenceError: error is not defined
    at /home/runner/.npm/_npx/1694/lib/node_modules/@orbit-love/stackoverflow/src/orbit.js:27:45
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by phazonoverload** [comment]
👀! I'll figure this out and have it fixed soon.

**Comment by phazonoverload** [comment]
I'm struggling to reproduce this but I have changed the way errors are displayed so this error should not be thrown in future. I'm going to close this, but if a similar issue persists feel free to open it again.

**Comment by phazonoverload** [comment]
I'll keep an eye on your runs over the next few days and see if anything like this appears again ❤️
